'use strict';

var util = require('util');

var codes = {
  '-3': 'ERR_ABORTED',
  '-10': 'ERR_ACCESS_DENIED',
  '-108': 'ERR_ADDRESS_INVALID',
  '-109': 'ERR_ADDRESS_UNREACHABLE',
  '-400': 'ERR_CACHE_MISS',
  '-202': 'ERR_CERT_AUTHORITY_INVALID',
  '-200': 'ERR_CERT_COMMON_NAME_INVALID',
  '-203': 'ERR_CERT_CONTAINS_ERRORS',
  '-201': 'ERR_CERT_DATE_INVALID',
  '-208': 'ERR_CERT_END',
  '-207': 'ERR_CERT_INVALID',
  '-204': 'ERR_CERT_NO_REVOCATION_MECHANISM',
  '-206': 'ERR_CERT_REVOKED',
  '-205': 'ERR_CERT_UNABLE_TO_CHECK_REVOCATION',
  '-103': 'ERR_CONNECTION_ABORTED',
  '-100': 'ERR_CONNECTION_CLOSED',
  '-104': 'ERR_CONNECTION_FAILED',
  '-102': 'ERR_CONNECTION_REFUSED',
  '-101': 'ERR_CONNECTION_RESET',
  '-301': 'ERR_DISALLOWED_URL_SCHEME',
  '-324': 'ERR_EMPTY_RESPONSE',
  '-2': 'ERR_FAILED',
  '-6': 'ERR_FILE_NOT_FOUND',
  '-8': 'ERR_FILE_TOO_BIG',
  '-501': 'ERR_INSECURE_RESPONSE',
  '-106': 'ERR_INTERNET_DISCONNECTED',
  '-4': 'ERR_INVALID_ARGUMENT',
  '-321': 'ERR_INVALID_CHUNKED_ENCODING',
  '-5': 'ERR_INVALID_HANDLE',
  '-320': 'ERR_INVALID_RESPONSE',
  '-300': 'ERR_INVALID_URL',
  '-322': 'ERR_METHOD_NOT_SUPPORTED',
  '-105': 'ERR_NAME_NOT_RESOLVED',
  '-112': 'ERR_NO_SSL_VERSIONS_ENABLED',
  '-11': 'ERR_NOT_IMPLEMENTED',
  '-325': 'ERR_RESPONSE_HEADERS_TOO_BIG',
  '-110': 'ERR_SSL_CLIENT_AUTH_CERT_NEEDED',
  '-107': 'ERR_SSL_PROTOCOL_ERROR',
  '-114': 'ERR_SSL_RENEGOTIATION_REQUESTED',
  '-113': 'ERR_SSL_VERSION_OR_CIPHER_MISMATCH',
  '-7': 'ERR_TIMED_OUT',
  '-310': 'ERR_TOO_MANY_REDIRECTS',
  '-111': 'ERR_TUNNEL_CONNECTION_FAILED',
  '-9': 'ERR_UNEXPECTED',
  '-323': 'ERR_UNEXPECTED_PROXY_AUTH',
  '-302': 'ERR_UNKNOWN_URL_SCHEME',
  '-312': 'ERR_UNSAFE_PORT',
  '-311': 'ERR_UNSAFE_REDIRECT'
};

function CefError(code) {
  this.name = 'CefError';
  this.code = codes[code] || null;
  this.message = util.format('CEF error "%s"', this.code);
  Error.captureStackTrace(this, CefError);
}
util.inherits(CefError, Error);

module.exports = CefError;
